all:
	#gcc -Wall -o eventfd_test eventfd_test.c -I../../outlib/libev-4.22 ../../outlib/libev-4.22/.libs/libev.a -lm
	gcc -o eventfd_test eventfd_test.c -I../../outlib/libev-4.22 ../../outlib/libev-4.22/.libs/libev.a -lm -lpthread
